CREATE TABLE country (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code CHAR(2) NOT NULL UNIQUE,
    name TEXT NOT NULL
);

CREATE TABLE city (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    country_id BIGINT NOT NULL REFERENCES country(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    position geography(point, 4326)
);
